### ISSUE TITLE
Integer values for table_id result in a TypeError

### ISSUE THREAD

**Issue by mwvaughn** [tapis-project/tapipy#26]
When I attempt to interact with a pgrest table via its table_id, which is defined as an integer type, tapipy throws an Exception. See this example:

```
from tapipy.tapis import Tapis
>>> t = Tapis(base_url='https://a2cps.tapis.io', username='vaughn', password='<REDACTED>')
>>> t.get_tokens()
>>> t.pgrest.get_table(table_id=33)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mwvaughn/src/A2CPS/python-vbr/env/lib/python3.8/site-packages/tapipy/tapis.py", line 1120, in __call__
    url = url.replace(s, p_val)
TypeError: replace() argument 2 must be str, not int
```

This can be remedied in client code by passing `str(table_id)` but in my opinion, tapipy should handle this for me. Looking at the code, it should be possible to simply change the line in `tapis.py` to

```python
url = url.replace(s, str(p_val))
```

**Comment by NotChristianGarcia** [comment]
Sorry for the wait. Fixed in 1.0.5. Deployed already.
