### ISSUE TITLE
Upload file does not work

### ISSUE THREAD

**Issue by georgiastuart** [tapis-project/tapipy#49]
```python
with open("experiment-results.hd5", "r") as f:
    t.files.upload("my-system", "/folderA/folderB/folderC/someFile.txt", f)
```

From [here](https://tapis.readthedocs.io/en/latest/technical/files.html?highlight=upload#file-uploads:~:text=with%20open(,%2C%20f)) results in the following error:

```
AttributeError: 'Resource' object has no attribute 'upload'
```

Inspecting the `t.files` object confirms that's the case. However, it has an `insert` method that raises a `NotImplementedError` when used along the lines of what's described [here](https://github.com/tapis-project/tapipy/blob/main/tapipy/resources/openapi_v3-files.yml#L243).

**Comment by NotChristianGarcia** [comment]
Just seeing this now, regarding this issue, tapipy has a working workaround for `t.files.insert` in the form of `t.upload`. It's a hard- coded workaround.

I'm not closing this issue as we will want to support the dynamically created function eventually.

**Comment by NotChristianGarcia** [comment]
Support for native `t.files.insert` introduced in 1.3.2. Commit: f72f5a812aaf51e7350d219d62e894c2aaaa8050
